inherit_gem:
  rubocop-rock: defaults.yml

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
  - Exclude
  - AllowedNames

AllCops:
  TargetRubyVersion: "2.5"

Style/MultilineMemoization:
    EnforcedStyle: braces

Style/StderrPuts:
    Enabled: false

Naming/PredicateName:
    Enabled: false

# Lots of false positive because of our class_eval-like blocks like e.g.
# new_submodel or stub. Propose a change to the cop's code to allow for
# custom methods before re-enabling
Lint/NestedMethodDefinition:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - '**/test/**/test_*.rb'
    - '**/test/**/*_test.rb'

Metrics/BlockLength:
  ExcludedMethods:
      - describe
      - it

Style/AccessModifierDeclarations:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
  - as

